#ifndef _AEC_POST_PROCESS_CONFIGURATION_H_
#define _AEC_POST_PROCESS_CONFIGURATION_H_

#define AEC_POST_PROCESSING_ON 1
#define AEC_SAVE_FAR			1

#define AEC_POST_PROCESSING_COH 0
#define AEC_POST_PROCESSING_NN  1
#define AEC_LN_PRECISION		20
#define AEC_EXP_PRECISION		20

#endif
